include 3rd_party/files.mk
include tools/freebsd/etc.rc.d/files.mk
include tools/yclgen/files.mk
include apps/yans/files.mk
include lib/util/files.mk
include lib/lua/files.mk
include lib/net/files.mk
include lib/ycl/files.mk
include apps/stored/files.mk
include apps/ethd/files.mk
include apps/fc2/files.mk
include apps/clid/files.mk
include apps/knegd/files.mk
include apps/kneg/files.mk
include apps/store/files.mk
include apps/dnstres/files.mk
include apps/scgi_demo/files.mk
include apps/sc2/files.mk
include apps/yansapi/files.mk
include data/yans/files.mk
include data/kneg/files.mk
include data/yans-fe/files.mk
