include tools/freebsd/etc.rc.d/files.mk
include tools/linux/systemd/files.mk
include tools/yclgen/files.mk
include lib/alloc/files.mk
include lib/util/files.mk
include lib/match/files.mk
include lib/net/files.mk
include lib/ycl/files.mk
include apps/stored/files.mk
include apps/expand-dst/files.mk
include apps/fc2/files.mk
include apps/clid/files.mk
include apps/knegd/files.mk
include apps/kneg/files.mk
include apps/store/files.mk
include apps/dnstres/files.mk
include apps/scgi_demo/files.mk
include apps/a2/files.mk
include apps/sc2/files.mk
include data/kneg/files.mk
include data/yans-fe/files.mk
include drivers/files.mk
include apps/sysinfoapi/files.mk
include apps/scan/files.mk
include apps/tcpctl/files.mk
include apps/deduptbl/files.mk
include apps/webfetch/files.mk
