include tools/freebsd/etc.rc.d/rules.mk
include tools/linux/systemd/rules.mk
include 3rd_party/rules.mk
include tools/yclgen/rules.mk
include apps/yans/rules.mk
include lib/util/rules.mk
include lib/lua/rules.mk
include lib/net/rules.mk
include lib/ycl/rules.mk
include apps/stored/rules.mk
include apps/ethd/rules.mk
include apps/expand-dst/rules.mk
include apps/fc2/rules.mk
include apps/clid/rules.mk
include apps/grab-banners/rules.mk
include apps/knegd/rules.mk
include apps/kneg/rules.mk
include apps/store/rules.mk
include apps/dnstres/rules.mk
include apps/scgi_demo/rules.mk
include apps/sc2/rules.mk
include data/yans/rules.mk
include data/yans-fe/rules.mk
include apps/sysinfoapi/rules.mk
include apps/mkreport/rules.mk
include apps/scan/rules.mk
