include tools/freebsd/etc.rc.d/rules.mk
include 3rd_party/rules.mk
include tools/yclgen/rules.mk
include apps/yans/rules.mk
include lib/util/rules.mk
include lib/lua/rules.mk
include lib/net/rules.mk
include lib/ycl/rules.mk
include apps/stored/rules.mk
include apps/ethd/rules.mk
include apps/fc2/rules.mk
include apps/clid/rules.mk
include apps/knegd/rules.mk
include apps/kneg/rules.mk
