#!/bin/sh

# PROVIDE: xsshd
# REQUIRE: LOGIN FILESYSTEMS
# KEYWORD: shutdown
# Copyright (c) 2019 Sebastian Cato
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

. /etc/rc.subr

name="xsshd"
desc="R/O sshd"
rcvar="xsshd_enable"
command="/usr/sbin/sshd"
command_args="-f /etc/ssh/xsshd_config"
start_precmd="sshd_precmd"
pidfile="/var/run/sshd.pid"

sshd_precmd() {
  local xsshd_dir="/var/xsshd"
  local keyfile="${xsshd_dir}/ssh_host_ed25519_key"
  [ -f "$keyfile" ] && return 0
  install -d -m 0700 ${xsshd_dir}
  /usr/bin/ssh-keygen -q -t ed25519 -f "$keyfile" -N ""
  /usr/bin/ssh-keygen -l -f "$keyfile.pub"
}

load_rc_config $name
run_rc_command "$1"

