#!/bin/sh

die() {
  printf '%s\n' "$1" >&2
  exit 1
}

: ${MBR:=/usr/obj/usr/src/sys/boot/i386/pmbr/pmbr}
: ${BOOTFS:=/usr/obj/usr/src/sys/boot/i386/gptboot/gptboot}
: ${ROOTFS:=$1}

[ -f "$MBR" ] || die "missing MBR"
[ -f "$BOOTFS" ] || die "missing BOOTFS"
[ -f "$ROOTFS" ] || die "missing ROOTFS"

: ${OUTFILE:=$2}
: ${OUTFILE:=$(basename "$ROOTFS" .img).qcow2}

mkimg \
    -s gpt \
    -f qcow2 \
    -b "$MBR" \
    -p "freebsd-boot/bootfs:=$BOOTFS" \
    -p "freebsd-ufs/rootfs:=$ROOTFS" \
    -o "$OUTFILE"
