#!/bin/sh -xe
# Copyright (c) 2019 Sebastian Cato
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

die() {
  printf '%s\n' "$1" >&2
  exit 1
}

mk_efiboot_img() {
  dd if=/dev/zero of=efiboot.img bs=4k count=200
  local device=`mdconfig -a -t vnode -f efiboot.img`
  newfs_msdos -F 12 -m 0xf8 /dev/$device
  mkdir efi
  mount -t msdosfs /dev/$device efi
  mkdir -p efi/efi/boot
  cp "$1/boot/loader.efi" efi/efi/boot/bootx64.efi
  umount efi
  rmdir efi
  mdconfig -d -u $device
}

[ -d "$1" ] || die "Missing workdir"
[ -z "$2" ] && die "Missing ISO name" 

WORKDIR=$1
ISO=$2
# Must be upper case
LABEL=STAIRSTEP
PUBLISHER=Stairstep

bootable=""

mk_efiboot_img "$WORKDIR"
echo "/dev/iso9660/$LABEL / cd9660 ro 0 0" > "$WORKDIR/etc/fstab"
makefs -t cd9660  -o "bootimage=i386;${WORKDIR}/boot/cdboot" -o no-emul-boot -o "bootimage=i386;efiboot.img" -o no-emul-boot -o platformid=efi -o rockridge -o label="$LABEL" -o publisher="$PUBLISHER" "$ISO" "$WORKDIR"
rm -f "$1/etc/fstab"
rm -f efiboot.img
