#!/bin/sh

die() {
  printf '%s\n' "$1" >&2
  exit 1
}

: ${FROMIMAGE:=$1}
: ${TOIMAGE:=$2}
: ${MOUNTPOINT:=$(pwd)/mntpoint}

[ -f "$FROMIMAGE" ] || die "missing FROMIMAGE"
[ -e "$MOUNTPOINT" ] && die "existing MOUNTPOINT"


# Create and mount TOIMAGE
cp "$FROMIMAGE" "$TOIMAGE" || die "failed to copy TOIMAGE"
DEVICE=$(mdconfig -f $TOIMAGE)
mkdir -p "$MOUNTPOINT"
mount "/dev/$DEVICE" "$MOUNTPOINT" || die "failed to mount $TOIMAGE"

# install Yans
DESTDIR=$MOUNTPOINT make -C ../../.. \
    install install-strip install-rcfiles || die "installation failed"

# install template files and setup users
DESTDIR=$MOUNTPOINT make install-skel
./setup-users "$MOUNTPOINT"

# Cleanup
umount "$MOUNTPOINT"
mdconfig -du "$DEVICE"
rmdir "$MOUNTPOINT"

# enable soft updates on the image
tunefs -n enable "$TOIMAGE" # enable soft updates

