#!/bin/sh
# Copyright (c) 2019 Sebastian Cato
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

die() {
  printf '%s\n' "$1" >&2
  exit 1
}

: ${FROMIMAGE:=$1}
: ${TOIMAGE:=$2}
: ${MOUNTPOINT:=$(pwd)/mntpoint}

[ -f "$FROMIMAGE" ] || die "missing FROMIMAGE"
[ -e "$MOUNTPOINT" ] && die "existing MOUNTPOINT"


# Create and mount TOIMAGE
cp "$FROMIMAGE" "$TOIMAGE" || die "failed to copy TOIMAGE"
DEVICE=$(mdconfig -f $TOIMAGE)
mkdir -p "$MOUNTPOINT"
mount "/dev/$DEVICE" "$MOUNTPOINT" || die "failed to mount $TOIMAGE"

# install Yans
DESTDIR=$MOUNTPOINT make -C ../../.. \
    install install-strip install-drivers install-rcfiles \
    || die "installation failed"

# install template files and setup users
DESTDIR=$MOUNTPOINT make install-skel
./setup-users "$MOUNTPOINT"

# Cleanup
umount "$MOUNTPOINT"
mdconfig -du "$DEVICE"
rmdir "$MOUNTPOINT"
