#!/bin/sh -xe


usage() {
  printf 'usage: %s <target>\n' "$0" >&2
  exit 1
}

: ${WORLDDIR:=/usr/src}
: ${RELEASEDIR:=$WORLDDIR/release}
: ${CONF:=$(pwd)/cloud.conf}
: ${FORMAT:=qcow2}
: ${VMSIZE:=256M}
: ${TARGET:=amd64}
: ${TARGET_ARCH:=amd64}
D=$1
[ -z "$D" ] && usage
case $D in
  [^/]*)
    printf 'target must be an absolute path\n' >&2
    usage
    ;;
esac

mkdir -p "$D"
#FIXME: update SRCCONF, KERNCONF
env "TARGET=$TARGET" "TARGET_ARCH=$TARGET_ARCH" \
    SRCCONF=/root/src.conf.installworld \
    KERNCONF=MYKERNEL \
    NOPKG=1 NOPORTS=1 NOSRC=1 NODOC=1 \
    "${RELEASEDIR}/scripts/mk-vmimage.sh" \
    -C "${RELEASEDIR}/tools/vmimage.subr" \
    -c "$CONF" \
    -d "$D" \
    -i "$D.img" \
    -s "$VMSIZE" \
    -f "$FORMAT" \
    -S "$WORLDDIR" \
    -o "$D.${FORMAT}"
