#!/bin/sh

die() {
  echo "$1" >&2
  exit 1
}

: ${DESTDIR:=$1}

[ -z "$DESTDIR" -o "$DESTDIR" = "/" ] && die "Missing/invalid DESTDIR"

# Add user daemons
pw -R "$DESTDIR" groupadd yans -g 666
for A in clid knegd stored sysinfoapi yansapi; do
  pw -R "$DESTDIR" useradd "$A" -d /nonexist -g yans -s /usr/sbin/nologin
done

# Add a default user: scan-user
# TODO: Make ssh pubkey configurable
userdir=$DESTDIR/usr/home/scan-user
pw -R "$DESTDIR" useradd scan-user -w none -u 666 -m -g yans -s /bin/sh
#install -m 0700 -d "$userdir/.ssh"
#cat <<EOF > "$userdir/.ssh/authorized_keys"
#<insert-pubkey-here>
#EOF

# Fix permission and ownership
#chown 666:666 "$userdir/.ssh/authorized_keys"
#chown 666:666 "$userdir/.ssh"
#chmod 600 "$userdir/.ssh/authorized_keys"
chmod 700 "$userdir"
chmod 700 "$DESTDIR/root"

# Remove unneeded users
pw -R "$DESTDIR" userdel toor
