#!/bin/sh

die() {
  echo "$1" >&2
  exit 1
}

: ${DESTDIR:=$1}

[ -z "$DESTDIR" -o "$DESTDIR" = "/" ] && die "Missing/invalid DESTDIR"

# Add user daemons
pw -R "$DESTDIR" groupadd yans -g 666
for A in clid ethd knegd stored sysinfoapi yansapi; do
  pw -R "$DESTDIR" useradd "$A" -d /nonexist -g yans -s /usr/sbin/nologin
done

# Add a default user: scan-user
# TODO: Make ssh pubkey configurable
userdir=$DESTDIR/usr/home/scan-user
pw -R "$DESTDIR" useradd scan-user -u 666 -m -g yans -s /bin/sh
install -m 0700 -d "$userdir/.ssh"
cat <<EOF > "$userdir/.ssh/authorized_keys"
ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAACAQC/5pzWzyyXO3hx95WLDRedFSVtZzmySbCkpw8cqwjmFPrdM6Vom2GN4MRzZ1ly4WaGhn/y+Jt2zqAO/hPWlA+EvGLOR3Q8pSrcT8/HqhiHvCG4N5CyX8bc6cWYmC8jvZgtHszqZOMPLCD9O/427F7QLQoS7hZJqrEHN1aDiweX//xRp8NAc95/2RyzZBGw5di6Y63JUB9uZibB2Bq3F2J9M2neqPdhMzRcB78WZr0T6oAOzmA0ZfUSpJjOutf5UjcQsAheXvtzOKkKTi1mTT6xeW8qSvNCPQjo6QWSGbFZxAcZwMjHzaXJEgc6UKK+BzQY/bdN4e/3WO3GDvEctG1wrX4F/QMfOMjQ4zOas1GcddRzAHsZmz9lTV171jJ1gT3jkGjejbITHUBHqUOF0ZFK2KzA+rj0H4XVXifXn4xhnYEi28gCKG/TY2+5zw8I24u+kqNcKlqBWa/vzokUJR/bVOJo6kYokcVwhL+icUqOPAppwXCHXzjuPl0B6aF0VNQR/B5fgVlyA84AdoeHnrbs5ew2gPzFdrpsFZP18jz1n8ti2gR3SwtJkhLjlBlhR/jWiTbmYj756GzzjabX/DkBidErfIwWga7kaAlyA+yCP56h3fOPT7pYN0JaivMCgVjr+RZsHDaqjCi4iDd9U8H+EeRgKFFVBkpe37vOs6PKgQ== scmc@resistance
EOF

# Fix permission and ownership
chown 666:666 "$userdir/.ssh/authorized_keys"
chown 666:666 "$userdir/.ssh"
chmod 600 "$userdir/.ssh/authorized_keys"
chmod 700 "$userdir"
chmod 700 "$DESTDIR/root"

# Remove unneeded users
pw -R "$DESTDIR" userdel toor
