#!/bin/sh
# Copyright (c) 2019 Sebastian Cato
#
# Permission is hereby granted, free of charge, to any person obtaining
# a copy of this software and associated documentation files (the
# "Software"), to deal in the Software without restriction, including
# without limitation the rights to use, copy, modify, merge, publish,
# distribute, sublicense, and/or sell copies of the Software, and to
# permit persons to whom the Software is furnished to do so, subject to
# the following conditions:
#
# The above copyright notice and this permission notice shall be
# included in all copies or substantial portions of the Software.
#
# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND,
# EXPRESS OR IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF
# MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE AND
# NONINFRINGEMENT. IN NO EVENT SHALL THE AUTHORS OR COPYRIGHT HOLDERS BE
# LIABLE FOR ANY CLAIM, DAMAGES OR OTHER LIABILITY, WHETHER IN AN ACTION
# OF CONTRACT, TORT OR OTHERWISE, ARISING FROM, OUT OF OR IN CONNECTION
# WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS IN THE SOFTWARE.

die() {
  echo "$1" >&2
  exit 1
}

: ${DESTDIR:=$1}

[ -z "$DESTDIR" -o "$DESTDIR" = "/" ] && die "Missing/invalid DESTDIR"

# Add user daemons
pw -R "$DESTDIR" groupadd yans -g 666
for A in clid knegd stored sysinfoapi yansapi; do
  pw -R "$DESTDIR" useradd "$A" -d /nonexist -g yans -s /usr/sbin/nologin
done

# Add a default user: scan-user
# TODO: Make ssh pubkey configurable
userdir=$DESTDIR/usr/home/scan-user
pw -R "$DESTDIR" useradd scan-user -w none -u 666 -m -g yans -s /bin/sh
#install -m 0700 -d "$userdir/.ssh"
#cat <<EOF > "$userdir/.ssh/authorized_keys"
#<insert-pubkey-here>
#EOF

# Fix permission and ownership
#chown 666:666 "$userdir/.ssh/authorized_keys"
#chown 666:666 "$userdir/.ssh"
#chmod 600 "$userdir/.ssh/authorized_keys"
chmod 700 "$userdir"
chmod 700 "$DESTDIR/root"

# Remove unneeded users
pw -R "$DESTDIR" userdel toor
