/* auto-generated by yclgen - DO NOT EDIT */
#ifndef YCLGEN_MSGS_H__
#define YCLGEN_MSGS_H__
#include <stddef.h>
#include <lib/ycl/ycl.h>

struct ycl_data {
  size_t len;
  const char *data;
};

struct ycl_msg_ethframe_req {
  long pps;
  const char *iface;
  const char *categories;
  const char *eth_src;
  const char *eth_dst;
  const char *ip_src;
  const char *ip_dsts;
  const char *port_dsts;
  struct ycl_data *custom_frames;
  size_t ncustom_frames;
};

struct ycl_msg_pcap_close {
};

struct ycl_msg_pcap_req {
  const char *iface;
  const char *filter;
};

struct ycl_msg_status_resp {
  const char *okmsg;
  const char *errmsg;
};

int ycl_msg_parse_ethframe_req(struct ycl_msg *msg,
    struct ycl_msg_ethframe_req *r);
int ycl_msg_create_ethframe_req(struct ycl_msg *msg,
    struct ycl_msg_ethframe_req *r);

int ycl_msg_parse_pcap_close(struct ycl_msg *msg,
    struct ycl_msg_pcap_close *r);
int ycl_msg_create_pcap_close(struct ycl_msg *msg,
    struct ycl_msg_pcap_close *r);

int ycl_msg_parse_pcap_req(struct ycl_msg *msg,
    struct ycl_msg_pcap_req *r);
int ycl_msg_create_pcap_req(struct ycl_msg *msg,
    struct ycl_msg_pcap_req *r);

int ycl_msg_parse_status_resp(struct ycl_msg *msg,
    struct ycl_msg_status_resp *r);
int ycl_msg_create_status_resp(struct ycl_msg *msg,
    struct ycl_msg_status_resp *r);

#endif /* YCLGEN_MSGS_H__ */
